FROM php:8.2-apache

# Copia os arquivos para o container
COPY . /var/www/html/

# Instala dependências PHP se necessário (ex: Composer)
RUN docker-php-ext-install pdo pdo_mysql
RUN apt-get update && apt-get install -y unzip git curl
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN composer install --no-dev
