FROM php:8.2-apache

RUN apt-get update && apt-get install -y \
    libzip-dev \
    libonig-dev \
    unzip \
    git \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-install pdo pdo_mysql mbstring zip

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

WORKDIR /var/www/html

COPY Server/ .

RUN rm -rf vendor
RUN composer clear-cache
RUN composer install --no-dev --optimize-autoloader

# Ajusta o DocumentRoot do Apache para a pasta public
RUN sed -i 's|/var/www/html|/var/www/html/public|g' /etc/apache2/sites-available/000-default.conf

# Habilita mod_rewrite (útil para Slim e outros frameworks)
RUN a2enmod rewrite

RUN chown -R www-data:www-data /var/www/html

EXPOSE 80
